"Cog: AdvancedUptime":
  - advanceduptime/*
"Cog: Codify":
  - codify/*
"Cog: Edition":
  - edition/*
"Cog: Dehoister":
  - dehoister/*
"Cog: NameGenerator":
  - namegenerator/*
"Cog: PingOverride":
  - pingoverride/*
"Cog: RAM":
  - ram/*
"Cog: SendCards":
  - sendcards/*
"Cog: Staff":
  - staff/*
"Cog: TextManipulator":
  - textmanipulator/*
"Cog: TimesTables":
  - timestables/*
"Cog: VoteChannel":
  - votechannel/*
"Category: Repository":
  - ./*
  - .github/*
  - .github/ISSUE_TEMPLATE/*
  - .utils/*
